version: '3'

services:
  node:
    image: node:latest
    container_name: node-app
    restart: always
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - PGUSER=root
      - PGPASSWORD=mypassword
      - PGDATABASE=mydatabase
      - PGHOST=db
      - PGPORT=5432
    depends_on:
      - db
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "npm install; npm start"

  db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    ports:
      - 5432:5432